# Generated by Django 3.0.3 on 2020-02-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=250)),
                ('fk_Lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crello.Lista')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='fk_Tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crello.Tablero'),
        ),
    ]
